version: "3.8"

services:
  db:
    image: postgres:15
    container_name: linea_base_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"  # Puerto externo 5434, pero dentro de Docker sigue siendo 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    networks:
      - app_network

  app:
    build: .
    container_name: linea_base_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: "us-east-1"
      SQS_QUEUE_CLIENT_URL: "arn:aws:sqs:us-east-1:142911054234:client-queue"
      
      DB_URL: "postgresql://postgres:1234@db:5432/postgres"  # Cambiado de localhost -> db     
      DB_HOST: "db"  # Nombre del servicio en Docker
      DB_PORT: "5432"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "1234"
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
