version: "3.8"

services:
  db:
    image: postgres:15
    container_name: linea_base_db
    restart: unless-stopped
    ports:
      - "5434:5432"  # expone PostgreSQL solo si es necesario , # Puerto externo 5434, pero dentro de Docker sigue siendo 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: linea_base_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    environment:
      DB_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      SQS_QUEUE_CLIENT_URL: ${SQS_QUEUE_CLIENT_URL}
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
